version: '3.7'
services:
  jenkins:
    build: myjenkins/
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1      
    volumes:
      - jenkins-home:/var/jenkins_home
      - docker-certs:/certs/client:ro
      - ./wordpress:/var/jenkins_home/wordpress
    depends_on:
      - docker  
  
  docker:
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    ports:
      - "80:80"  
    volumes:
      - docker-certs:/certs/client 
      - jenkins-home:/var/jenkins_home
      - docker-data:/var/lib/docker         
volumes:
  jenkins-home:
  docker-certs:
  docker-data: 
